application: flexirod
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest

builtins:
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: static/img/24.png
  upload: static/img/24.png

- url: /static
  static_dir: static

- url: /partial
  static_dir: partial

- url: /admin.*
  script: controller.admin.app
  login: admin

- url: /login
  script: controller.controller.app

- url: /
  script: controller.controller.app

- url: /public/.*
  script: controller.controller.app

- url: .*
  script: controller.controller.app
  login: required


